src/app.py
from flask import Flask
from .routes import orders_routes, product_routes

app = Flask(__name__)
app.register_blueprint(orders_routes.main, url_prefix='/api/order')
app.register_blueprint(product_routes.main, url_prefix='/api/product')

if __name__ == '__main__':
    app.run()

src/controllers/orders_controller.py
from src.classes.order import Order
from src.classes.order_detail import OrderDetail
from src.classesDao.order_dao import OrderDao
from src.classesDao.order_detail_dao import OrderDetailDao
from src.classesDao.customer_id_dao import CustomerProductDao
from src.classesDao.product_dao import ProductDao
from src.util.logger_base import log

from decouple import config
from datetime import datetime


class OrderController:

    @classmethod
    def select(cls):
        return OrderDao.select()
    @classmethod
    def create_order(self, info_order):
        try:

            customer_id = info_order['customer_id']
            delivery_address = info_order['delivery_address']
            products_order = info_order['products']
            MAX_QUANTITY = int(config('MAX_QUANTITY'))

            # products permitted
            permitted_products_reg = CustomerProductDao().selec_by_customer(customer_id)
            permitted_products = [int(cp.product_id)
                                  for cp in permitted_products_reg]
            products_db = []

            for product in products_order:
                product_id = product['product_id']
                prod_quantity = product['quantity']

                if product_id not in permitted_products or prod_quantity > MAX_QUANTITY:
                    error = f'permitted products {str(permitted_products)} max quantity {MAX_QUANTITY}'
                    log.error(error)
                    raise ValueError(error)
                else:
                    productDB = ProductDao().select_by_id(product_id)
                    products_db.append(productDB)

            # get total order
            total = self.get_total_order(
                products_order=products_order, products=products_db)

            # create order
            creation_date = datetime.now()
            order1 = Order(customer_id, creation_date,
                           delivery_address, total)

            order_id = OrderDao().insert(order1)

            # create details order
            for product in products_db:
                product_id = product.product_id
                quantity = [
                    product['quantity'] for product in products_order if product['product_id'] == product_id
                ][0]

                description = product.description
                price = product.price
                order_detail1 = OrderDetail(
                    order_id, product_id, description, price, quantity)

                OrderDetailDao.insert(order_detail1)

            return f'insert row with id {order_id}'

        except Exception as e:
            log.error(f'error in create order {e}')
            raise e

    @classmethod
    def get_customer_orders_report(cls, customer_id, date1, date2):
        try:
            customer_orders = OrderDao.select_customer_orders_report(
                customer_id, date1, date2)

            if not len(customer_orders):
                raise ValueError(
                    f'customer {customer_id} has no orders in this range')

            return {"customer_id": customer_id, "orders": customer_orders}

        except Exception as e:
            log.error(f'Error in getting customer order {e}')
            raise e

    def get_total_order(products_order, products):

        log.info(products)
        # create tuple (quantity, price) of product
        quantity_prices = [(prod_info['quantity'], prod.price)
                           for prod_info in products_order for prod in products if prod_info['product_id'] == prod.product_id]
        total = 0
        for quantity_price in quantity_prices:
            total += quantity_price[0] * quantity_price[1]
        return total

src/controllers/product_controller.py
from src.classesDao.product_dao import ProductDao 

class ProductController:

    @classmethod
    def select(cls):
        products = ProductDao.select()
        return products

    @classmethod
    def select_one(cls, id):
        product = ProductDao.select_by_id(id)
        return product

    @classmethod
    def update_price(cls, request_prod):
        product_id = request_prod['product_id']
        new_price = request_prod['price']
        product = ProductDao().select_by_id(product_id)
        product.price = new_price
        response = ProductDao().update_price(product)
        return response

src/routes/orders_routes.py
#from src import app
from flask import jsonify, render_template, request, Blueprint
from src.controllers.orders_controller import OrderController

main = Blueprint('order_blueprint', __name__)


@main.route('', methods=['GET', 'POST'])
def get_orders():
    try:
        response = ''
        if request.method == 'POST':
            request_order = request.get_json()
            response = OrderController.create_order(request_order)
        else:
            response = OrderController.select()
        return jsonify({"success": True, "data": response})

    except Exception as e:
        return jsonify({"success": False, "message": str(e)}), 500


# @main.route('/<int:customer_id>/<date1>/<date2>')
# def get_customer_orders(customer_id, date1, date2):
@main.route('/')
def get_customer_orders():
    try:
        customer_id = request.args.get('customer_id')
        date1 = request.args.get('date1')
        date2 = request.args.get('date2')
        response = OrderController.get_customer_orders_report(
            customer_id, date1, date2)
        return jsonify({"success": True, "data": response})

    except Exception as e:
        return jsonify({"success": False, "message": str(e)}), 500


@main.route('/report/')
def get_customer_orders_report():
    try:
        customer_id = request.args.get('customer_id')
        date1 = request.args.get('date1')
        date2 = request.args.get('date2')
        response = OrderController.get_customer_orders_report(
            customer_id, date1, date2)
        return render_template('table.html', products=response['orders'])

    except Exception as e:
        return jsonify({"success": False, "message": str(e)}), 500

src/routes/product_routes.py
from urllib import response
from flask import redirect, render_template, request, Blueprint, url_for
from src.classesDao.product_dao import ProductDao
from src.controllers.product_controller import ProductController

main = Blueprint('product_route', __name__)


@main.route('')
def get_products():
    try:
        response = ProductController.select()
        return {"success": True, "data": response}
    except Exception as e:
        return {"success": False, "message": str(e)}


@main.route('/admin/<int:id>')
def get_product(id):
    try:
        product = ProductController.select_one(id)
        return render_template('product_detail.html', product=product)

    except Exception as e:
        return {"success": False, "message": str(e)}


@main.route('', methods=['PUT', 'POST'])
def update_product():
    try:

        if request.method == 'POST':
            request_prod = request.form.to_dict()
            ProductController.update_price(request_prod)
            return redirect(url_for('product_route.show_products'))

        request_prod = request.json
        response = ProductController.update_price(request_prod)
        return {"success": True, "data": f'{response} product updated successfully'}

    except Exception as e:
        return {"success": False, "message": str(e)}


@main.route('/admin')
def show_products():
    try:
        products = ProductController.select()
        return render_template('products.html', products=products)
    except Exception as e:
        return {"success": False, "message": str(e)}

src/templates/product_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>product_detail</title>
</head>
<body>
    <h1>Editar producto</h1>
    <div>
        <div>Id : {{product.product_id}}</div>
        <div>Nombre : {{product.name}}</div>
        <div>descripción : {{product.description}}</div>

        <form action="/api/product" method="post">
            <input type="text" id="product_id" name="product_id" value="{{product.product_id}}" hidden>
            <label for="price">precio</label>
            <input type="text" name="price" id="price" value="{{product.price}}">
            <br>
            <input type="submit" value="Actualizar precio">
        </form>
    </div>
</body>
</html>

src/templates/products.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>products</title>
</head>

<body>
    <div>
        <table border="1">
            <thead>
                <tr>
                    <th>id</th>
                    <th>name</th>
                    <th>description</th>
                    <th>price</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for product in products %}
                <tr>
                    <td>{{product.product_id}}</td>
                    <td>{{product.name}}</td>
                    <td>{{product.description}}</td>
                    <td>{{product.price}}</td>
                    <td> <a href="{{ url_for('product_route.get_product', id= product.product_id) }}">Editar</a> </td>
                </tr>
                {% endfor%}
            </tbody>
        </table>
    </div>
</body>

</html>

src/templates/table.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>table</title>
</head>
<body>
    <div>
        <table border="1">
            <thead>
                <tr>
                    <th>Creation Date</th>
                    <th>Order ID</th>
                    <th>Total $</th>
                    <th>Delivery Address</th>
                    <th>Products</th>
                </tr>
            </thead>
            <tbody>
                {% for product in products %}
                <tr>
                    <td> {{product.creation_date}} </td>
                    <td> {{product.order_id}} </td>
                    <td> {{product.total}} </td>
                    <td> {{product.delivery_address}} </td>
                    <td> {{product.products}} </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
</html>